name: Node CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: on Pull
      if: github.event_name == 'pull_request'
      run: echo pull!
    - name: on Push
      if: github.event_name == 'push'
      run: echo push!